export const fetchConsumerHistory = async (email) => {
    console.log(`Fetching history for: ${email}`);

    return new Promise((resolve) => {
        setTimeout(() => {
            resolve([
                {
                    "id": 1,
                    "flight": "Flight-100",
                    "airline": "JetX Airways",
                    "date": "2024-01-01",
                    "departure": "New York",
                    "destination": "Seattle",
                    "departure_time": "01:00 AM",
                    "arrival_time": "04:00 PM",
                    "flight_duration": 1.0,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 1",
                    "total_passengers": 8,
                    " ": "1A",
                    " ": "REF-1000",
                    " ": "Credit Card",
                    " ": 15, 
                    " ": "A1",
                    "terminal": "1",
                    "layover": "1 Stop",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 2,
                    "flight": "Flight-101",
                    "airline": "SkyJet Airlines",
                    "date": "2024-02-02",
                    "departure": "Chicago",
                    "destination": "New York",
                    "departure_time": "02:05 PM",
                    "arrival_time": "05:07 AM",
                    "flight_duration": 2.5,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "total_passengers": 8,
                    
                    "terminal": "2",
                    "layover": "3 stops",
                    
                },
                {
                    "id": 3,
                    "flight": "Flight-102",
                    "airline": "AirLux",
                    "date": "2024-03-03",
                    "departure": "Miami",
                    "destination": "Chicago",
                    "departure_time": "03:10 AM",
                    "arrival_time": "06:14 PM",
                    "flight_duration": 4.0,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "total_passengers": 8,
                   
                    "terminal": "3",
                    "layover": "3 stops",
                },
                {
                    "id": 4,
                    "flight": "Flight-103",
                    "airline": "Elite Airways",
                    "date": "2024-04-04",
                    "departure": "Dallas",
                    "destination": "Dallas",
                    "departure_time": "04:15 PM",
                    "arrival_time": "07:21 AM",
                    "flight_duration": 4.0,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "total_passengers": 8,
                   
                    "terminal": "4",
                    "layover": "1 Stop",
                },
                {
                    "id": 5,
                    "flight": "Flight-104",
                    "airline": "PrivateFly",
                    "date": "2024-05-05",
                    "departure": "Los Angeles",
                    "destination": "Denver",
                    "departure_time": "05:20 AM",
                    "arrival_time": "08:28 PM",
                    "flight_duration": 5.5,
                    "status": "Completed",
                    "amount_earn": 700,
                    "total_passengers": 8,

                    "terminal": "1",
                    "layover": "3 stops",

                },
                {
                    "id": 6,
                    "flight": "Flight-105",
                    "airline": "SkyHigh",
                    "date": "2024-06-06",
                    "departure": "San Francisco",
                    "destination": "Boston",
                    "departure_time": "06:25 PM",
                    "arrival_time": "09:35 AM",
                    "flight_duration": 2.0,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "total_passengers": 8,

                    "terminal": "2",
                    "layover": "3 stops",

                },
                {
                    "id": 7,
                    "flight": "Flight-106",
                    "airline": "AirElite",
                    "date": "2024-07-07",
                    "departure": "Seattle",
                    "destination": "Houston",
                    "departure_time": "07:30 AM",
                    "arrival_time": "10:42 PM",
                    "flight_duration": 2.0,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "total_passengers": 8,

                    "terminal": "3",
                    "layover": "1 Stop",

                },
                {
                    "id": 8,
                    "flight": "Flight-107",
                    "airline": "LuxAir",
                    "date": "2024-08-08",
                    "departure": "Denver",
                    "destination": "Los Angeles",
                    "departure_time": "08:35 PM",
                    "arrival_time": "11:49 AM",
                    "flight_duration": 3.5,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 8",
                    "total_passengers": 9,
                    " ": "8B",
                    " ": "REF-1007",
                    " ": "PayPal",
                    " ": 30,
                    " ": "C8",
                    "terminal": "4",
                    "layover": "2 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 9,
                    "flight": "Flight-108",
                    "airline": "SwiftJet",
                    "date": "2024-09-09",
                    "departure": "Boston",
                    "destination": "Miami",
                    "departure_time": "09:40 AM",
                    "arrival_time": "12:56 PM",
                    "flight_duration": 5.0,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 9",
                    "total_passengers": 11,
                    " ": "9C",
                    " ": "REF-1008",
                    " ": "Bank Transfer",
                    " ": 15,
                    " ": "D9",
                    "terminal": "1",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 10,
                    "flight": "Flight-109",
                    "airline": "JetX Airways",
                    "date": "2024-10-10",
                    "departure": "Houston",
                    "destination": "San Francisco",
                    "departure_time": "10:45 PM",
                    "arrival_time": "01:03 AM",
                    "flight_duration": 5.0,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 10",
                    "total_passengers": 6,
                    " ": "10D",
                    " ": "REF-1009",
                    " ": "Credit Card",
                    " ": 20,
                    " ": "E10",
                    "terminal": "2",
                    "layover": "1 Stop",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                },
                {
                    "id": 11,
                    "flight": "Flight-110",
                    "airline": "SkyJet Airlines",
                    "date": "2024-11-11",
                    "departure": "New York",
                    "destination": "Seattle",
                    "departure_time": "11:50 AM",
                    "arrival_time": "02:10 PM",
                    "flight_duration": 1.5,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "passenger_name": "Passenger 11",
                    "total_passengers": 9,
                    " ": "11E",
                    " ": "REF-1010",
                    " ": "PayPal",
                    " ": 25,
                    " ": "A11",
                    "terminal": "3",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "Silver Member"
                },
                {
                    "id": 12,
                    "flight": "Flight-111",
                    "airline": "AirLux",
                    "date": "2024-12-12",
                    "departure": "Chicago",
                    "destination": "New York",
                    "departure_time": "12:55 PM",
                    "arrival_time": "03:17 AM",
                    "flight_duration": 3.0,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 12",
                    "total_passengers": 11,
                    " ": "12F",
                    " ": "REF-1011",
                    " ": "Bank Transfer",
                    " ": 30,
                    " ": "B12",
                    "terminal": "4",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 13,
                    "flight": "Flight-112",
                    "airline": "Elite Airways",
                    "date": "2024-01-13",
                    "departure": "Miami",
                    "destination": "Chicago",
                    "departure_time": "01:00 AM",
                    "arrival_time": "04:24 PM",
                    "flight_duration": 3.0,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 13",
                    "total_passengers": 6,
                    " ": "13A",
                    " ": "REF-1012",
                    " ": "Credit Card",
                    " ": 15,
                    " ": "C13",
                    "terminal": "1",
                    "layover": "1 Stop",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 14,
                    "flight": "Flight-113",
                    "airline": "PrivateFly",
                    "date": "2024-02-14",
                    "departure": "Dallas",
                    "destination": "Dallas",
                    "departure_time": "02:05 PM",
                    "arrival_time": "05:31 AM",
                    "flight_duration": 4.5,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 14",
                    "total_passengers": 9,
                    " ": "14B",
                    " ": "REF-1013",
                    " ": "PayPal",
                    " ": 20,
                    " ": "D14",
                    "terminal": "2",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                },
                {
                    "id": 15,
                    "flight": "Flight-114",
                    "airline": "SkyHigh",
                    "date": "2024-03-15",
                    "departure": "Los Angeles",
                    "destination": "Denver",
                    "departure_time": "03:10 AM",
                    "arrival_time": "06:38 PM",
                    "flight_duration": 6.0,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "passenger_name": "Passenger 15",
                    "total_passengers": 11,
                    " ": "15C",
                    " ": "REF-1014",
                    " ": "Bank Transfer",
                    " ": 25,
                    " ": "E15",
                    "terminal": "3",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "Silver Member"
                },
                {
                    "id": 16,
                    "flight": "Flight-115",
                    "airline": "AirElite",
                    "date": "2024-04-16",
                    "departure": "San Francisco",
                    "destination": "Boston",
                    "departure_time": "04:15 PM",
                    "arrival_time": "07:45 AM",
                    "flight_duration": 1.0,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 16",
                    "total_passengers": 6,
                    " ": "16D",
                    " ": "REF-1015",
                    " ": "Credit Card",
                    " ": 30,
                    " ": "A16",
                    "terminal": "4",
                    "layover": "1 Stop",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 17,
                    "flight": "Flight-116",
                    "airline": "LuxAir",
                    "date": "2024-05-17",
                    "departure": "Seattle",
                    "destination": "Houston",
                    "departure_time": "05:20 AM",
                    "arrival_time": "08:52 PM",
                    "flight_duration": 2.5,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 17",
                    "total_passengers": 9,
                    " ": "17E",
                    " ": "REF-1016",
                    " ": "PayPal",
                    " ": 15,
                    " ": "B17",
                    "terminal": "1",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 18,
                    "flight": "Flight-117",
                    "airline": "SwiftJet",
                    "date": "2024-06-18",
                    "departure": "Denver",
                    "destination": "Los Angeles",
                    "departure_time": "06:25 PM",
                    "arrival_time": "09:59 AM",
                    "flight_duration": 4.0,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 18",
                    "total_passengers": 11,
                    " ": "18F",
                    " ": "REF-1017",
                    " ": "Bank Transfer",
                    " ": 20,
                    " ": "C18",
                    "terminal": "2",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                },
                {
                    "id": 19,
                    "flight": "Flight-118",
                    "airline": "JetX Airways",
                    "date": "2024-07-19",
                    "departure": "Boston",
                    "destination": "Miami",
                    "departure_time": "07:30 AM",
                    "arrival_time": "10:06 PM",
                    "flight_duration": 4.0,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "passenger_name": "Passenger 19",
                    "total_passengers": 6,
                    " ": "19A",
                    " ": "REF-1018",
                    " ": "Credit Card",
                    " ": 25,
                    " ": "D19",
                    "terminal": "3",
                    "layover": "1 Stop",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "Silver Member"
                },
                {
                    "id": 20,
                    "flight": "Flight-119",
                    "airline": "SkyJet Airlines",
                    "date": "2024-08-20",
                    "departure": "Houston",
                    "destination": "San Francisco",
                    "departure_time": "08:35 PM",
                    "arrival_time": "11:13 AM",
                    "flight_duration": 5.5,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 20",
                    "total_passengers": 9,
                    " ": "20B",
                    " ": "REF-1019",
                    " ": "PayPal",
                    " ": 30,
                    " ": "E20",
                    "terminal": "4",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 21,
                    "flight": "Flight-120",
                    "airline": "AirLux",
                    "date": "2024-09-21",
                    "departure": "New York",
                    "destination": "Seattle",
                    "departure_time": "09:40 AM",
                    "arrival_time": "12:20 PM",
                    "flight_duration": 2.0,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 21",
                    "total_passengers": 11,
                    " ": "21C",
                    " ": "REF-1020",
                    " ": "Bank Transfer",
                    " ": 15,
                    " ": "A1",
                    "terminal": "1",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 22,
                    "flight": "Flight-121",
                    "airline": "Elite Airways",
                    "date": "2024-10-22",
                    "departure": "Chicago",
                    "destination": "New York",
                    "departure_time": "10:45 PM",
                    "arrival_time": "01:27 AM",
                    "flight_duration": 2.0,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 22",
                    "total_passengers": 6,
                    " ": "22D",
                    " ": "REF-1021",
                    " ": "Credit Card",
                    " ": 20,
                    " ": "B2",
                    "terminal": "2",
                    "layover": "1 Stop",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                },
                {
                    "id": 23,
                    "flight": "Flight-122",
                    "airline": "PrivateFly",
                    "date": "2024-11-23",
                    "departure": "Miami",
                    "destination": "Chicago",
                    "departure_time": "11:50 AM",
                    "arrival_time": "02:34 PM",
                    "flight_duration": 3.5,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "passenger_name": "Passenger 23",
                    "total_passengers": 9,
                    " ": "23E",
                    " ": "REF-1022",
                    " ": "PayPal",
                    " ": 25,
                    " ": "C3",
                    "terminal": "3",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "Silver Member"
                },
                {
                    "id": 24,
                    "flight": "Flight-123",
                    "airline": "SkyHigh",
                    "date": "2024-12-24",
                    "departure": "Dallas",
                    "destination": "Dallas",
                    "departure_time": "12:55 PM",
                    "arrival_time": "03:41 AM",
                    "flight_duration": 5.0,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 24",
                    "total_passengers": 11,
                    " ": "24F",
                    " ": "REF-1023",
                    " ": "Bank Transfer",
                    " ": 30,
                    " ": "D4",
                    "terminal": "4",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 25,
                    "flight": "Flight-124",
                    "airline": "AirElite",
                    "date": "2024-01-25",
                    "departure": "Los Angeles",
                    "destination": "Denver",
                    "departure_time": "01:00 AM",
                    "arrival_time": "04:48 PM",
                    "flight_duration": 5.0,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 25",
                    "total_passengers": 6,
                    " ": "25A",
                    " ": "REF-1024",
                    " ": "Credit Card",
                    " ": 15,
                    " ": "E5",
                    "terminal": "1",
                    "layover": "1 Stop",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 26,
                    "flight": "Flight-125",
                    "airline": "LuxAir",
                    "date": "2024-02-26",
                    "departure": "San Francisco",
                    "destination": "Boston",
                    "departure_time": "02:05 PM",
                    "arrival_time": "05:55 AM",
                    "flight_duration": 1.5,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 26",
                    "total_passengers": 9,
                    " ": "26B",
                    " ": "REF-1025",
                    " ": "PayPal",
                    " ": 20,
                    " ": "A6",
                    "terminal": "2",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                },
                {
                    "id": 27,
                    "flight": "Flight-126",
                    "airline": "SwiftJet",
                    "date": "2024-03-27",
                    "departure": "Seattle",
                    "destination": "Houston",
                    "departure_time": "03:10 AM",
                    "arrival_time": "06:02 PM",
                    "flight_duration": 3.0,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "passenger_name": "Passenger 27",
                    "total_passengers": 11,
                    " ": "27C",
                    " ": "REF-1026",
                    " ": "Bank Transfer",
                    " ": 25,
                    " ": "B7",
                    "terminal": "3",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "Silver Member"
                },
                {
                    "id": 28,
                    "flight": "Flight-127",
                    "airline": "JetX Airways",
                    "date": "2024-04-28",
                    "departure": "Denver",
                    "destination": "Los Angeles",
                    "departure_time": "04:15 PM",
                    "arrival_time": "07:09 AM",
                    "flight_duration": 3.0,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 28",
                    "total_passengers": 6,
                    " ": "28D",
                    " ": "REF-1027",
                    " ": "Credit Card",
                    " ": 30,
                    " ": "C8",
                    "terminal": "4",
                    "layover": "1 Stop",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 29,
                    "flight": "Flight-128",
                    "airline": "SkyJet Airlines",
                    "date": "2024-05-01",
                    "departure": "Boston",
                    "destination": "Miami",
                    "departure_time": "05:20 AM",
                    "arrival_time": "08:16 PM",
                    "flight_duration": 4.5,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 29",
                    "total_passengers": 9,
                    " ": "29E",
                    " ": "REF-1028",
                    " ": "PayPal",
                    " ": 15,
                    " ": "D9",
                    "terminal": "1",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 30,
                    "flight": "Flight-129",
                    "airline": "AirLux",
                    "date": "2024-06-02",
                    "departure": "Houston",
                    "destination": "San Francisco",
                    "departure_time": "06:25 PM",
                    "arrival_time": "09:23 AM",
                    "flight_duration": 6.0,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 30",
                    "total_passengers": 11,
                    " ": "30F",
                    " ": "REF-1029",
                    " ": "Bank Transfer",
                    " ": 20,
                    " ": "E10",
                    "terminal": "2",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                },
                {
                    "id": 31,
                    "flight": "Flight-130",
                    "airline": "Elite Airways",
                    "date": "2024-07-03",
                    "departure": "New York",
                    "destination": "Seattle",
                    "departure_time": "07:30 AM",
                    "arrival_time": "10:30 PM",
                    "flight_duration": 1.0,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "passenger_name": "Passenger 31",
                    "total_passengers": 6,
                    " ": "1A",
                    " ": "REF-1030",
                    " ": "Credit Card",
                    " ": 25,
                    " ": "A11",
                    "terminal": "3",
                    "layover": "1 Stop",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "Silver Member"
                },
                {
                    "id": 32,
                    "flight": "Flight-131",
                    "airline": "PrivateFly",
                    "date": "2024-08-04",
                    "departure": "Chicago",
                    "destination": "New York",
                    "departure_time": "08:35 PM",
                    "arrival_time": "11:37 AM",
                    "flight_duration": 2.5,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 32",
                    "total_passengers": 9,
                    " ": "2B",
                    " ": "REF-1031",
                    " ": "PayPal",
                    " ": 30,
                    " ": "B12",
                    "terminal": "4",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 33,
                    "flight": "Flight-132",
                    "airline": "SkyHigh",
                    "date": "2024-09-05",
                    "departure": "Miami",
                    "destination": "Chicago",
                    "departure_time": "09:40 AM",
                    "arrival_time": "12:44 PM",
                    "flight_duration": 4.0,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 33",
                    "total_passengers": 11,
                    " ": "3C",
                    " ": "REF-1032",
                    " ": "Bank Transfer",
                    " ": 15,
                    " ": "C13",
                    "terminal": "1",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 34,
                    "flight": "Flight-133",
                    "airline": "AirElite",
                    "date": "2024-10-06",
                    "departure": "Dallas",
                    "destination": "Dallas",
                    "departure_time": "10:45 PM",
                    "arrival_time": "01:51 AM",
                    "flight_duration": 4.0,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 34",
                    "total_passengers": 6,
                    " ": "4D",
                    " ": "REF-1033",
                    " ": "Credit Card",
                    " ": 20,
                    " ": "D14",
                    "terminal": "2",
                    "layover": "1 Stop",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                },
                {
                    "id": 35,
                    "flight": "Flight-134",
                    "airline": "LuxAir",
                    "date": "2024-11-07",
                    "departure": "Los Angeles",
                    "destination": "Denver",
                    "departure_time": "11:50 AM",
                    "arrival_time": "02:58 PM",
                    "flight_duration": 5.5,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "passenger_name": "Passenger 35",
                    "total_passengers": 9,
                    " ": "5E",
                    " ": "REF-1034",
                    " ": "PayPal",
                    " ": 25,
                    " ": "E15",
                    "terminal": "3",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "Silver Member"
                },
                {
                    "id": 36,
                    "flight": "Flight-135",
                    "airline": "SwiftJet",
                    "date": "2024-12-08",
                    "departure": "San Francisco",
                    "destination": "Boston",
                    "departure_time": "12:55 PM",
                    "arrival_time": "03:05 AM",
                    "flight_duration": 2.0,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 36",
                    "total_passengers": 11,
                    " ": "6F",
                    " ": "REF-1035",
                    " ": "Bank Transfer",
                    " ": 30,
                    " ": "A16",
                    "terminal": "4",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 37,
                    "flight": "Flight-136",
                    "airline": "JetX Airways",
                    "date": "2024-01-09",
                    "departure": "Seattle",
                    "destination": "Houston",
                    "departure_time": "01:00 AM",
                    "arrival_time": "04:12 PM",
                    "flight_duration": 2.0,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 37",
                    "total_passengers": 6,
                    " ": "7A",
                    " ": "REF-1036",
                    " ": "Credit Card",
                    " ": 15,
                    " ": "B17",
                    "terminal": "1",
                    "layover": "1 Stop",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 38,
                    "flight": "Flight-137",
                    "airline": "SkyJet Airlines",
                    "date": "2024-02-10",
                    "departure": "Denver",
                    "destination": "Los Angeles",
                    "departure_time": "02:05 PM",
                    "arrival_time": "05:19 AM",
                    "flight_duration": 3.5,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 38",
                    "total_passengers": 9,
                    " ": "8B",
                    " ": "REF-1037",
                    " ": "PayPal",
                    " ": 20,
                    " ": "C18",
                    "terminal": "2",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                },
                {
                    "id": 39,
                    "flight": "Flight-138",
                    "airline": "AirLux",
                    "date": "2024-03-11",
                    "departure": "Boston",
                    "destination": "Miami",
                    "departure_time": "03:10 AM",
                    "arrival_time": "06:26 PM",
                    "flight_duration": 5.0,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "passenger_name": "Passenger 39",
                    "total_passengers": 11,
                    " ": "9C",
                    " ": "REF-1038",
                    " ": "Bank Transfer",
                    " ": 25,
                    " ": "D19",
                    "terminal": "3",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "Silver Member"
                },
                {
                    "id": 40,
                    "flight": "Flight-139",
                    "airline": "Elite Airways",
                    "date": "2024-04-12",
                    "departure": "Houston",
                    "destination": "San Francisco",
                    "departure_time": "04:15 PM",
                    "arrival_time": "07:33 AM",
                    "flight_duration": 5.0,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 40",
                    "total_passengers": 6,
                    " ": "10D",
                    " ": "REF-1039",
                    " ": "Credit Card",
                    " ": 30,
                    " ": "E20",
                    "terminal": "4",
                    "layover": "1 Stop",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 41,
                    "flight": "Flight-140",
                    "airline": "PrivateFly",
                    "date": "2024-05-13",
                    "departure": "New York",
                    "destination": "Seattle",
                    "departure_time": "05:20 AM",
                    "arrival_time": "08:40 PM",
                    "flight_duration": 1.5,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 41",
                    "total_passengers": 9,
                    " ": "11E",
                    " ": "REF-1040",
                    " ": "PayPal",
                    " ": 15,
                    " ": "A1",
                    "terminal": "1",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 42,
                    "flight": "Flight-141",
                    "airline": "SkyHigh",
                    "date": "2024-06-14",
                    "departure": "Chicago",
                    "destination": "New York",
                    "departure_time": "06:25 PM",
                    "arrival_time": "09:47 AM",
                    "flight_duration": 3.0,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 42",
                    "total_passengers": 11,
                    " ": "12F",
                    " ": "REF-1041",
                    " ": "Bank Transfer",
                    " ": 20,
                    " ": "B2",
                    "terminal": "2",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                },
                {
                    "id": 43,
                    "flight": "Flight-142",
                    "airline": "AirElite",
                    "date": "2024-07-15",
                    "departure": "Miami",
                    "destination": "Chicago",
                    "departure_time": "07:30 AM",
                    "arrival_time": "10:54 PM",
                    "flight_duration": 3.0,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "passenger_name": "Passenger 43",
                    "total_passengers": 6,
                    " ": "13A",
                    " ": "REF-1042",
                    " ": "Credit Card",
                    " ": 25,
                    " ": "C3",
                    "terminal": "3",
                    "layover": "1 Stop",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "Silver Member"
                },
                {
                    "id": 44,
                    "flight": "Flight-143",
                    "airline": "LuxAir",
                    "date": "2024-08-16",
                    "departure": "Dallas",
                    "destination": "Dallas",
                    "departure_time": "08:35 PM",
                    "arrival_time": "11:01 AM",
                    "flight_duration": 4.5,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 44",
                    "total_passengers": 9,
                    " ": "14B",
                    " ": "REF-1043",
                    " ": "PayPal",
                    " ": 30,
                    " ": "D4",
                    "terminal": "4",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 45,
                    "flight": "Flight-144",
                    "airline": "SwiftJet",
                    "date": "2024-09-17",
                    "departure": "Los Angeles",
                    "destination": "Denver",
                    "departure_time": "09:40 AM",
                    "arrival_time": "12:08 PM",
                    "flight_duration": 6.0,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 45",
                    "total_passengers": 11,
                    " ": "15C",
                    " ": "REF-1044",
                    " ": "Bank Transfer",
                    " ": 15,
                    " ": "E5",
                    "terminal": "1",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 46,
                    "flight": "Flight-145",
                    "airline": "JetX Airways",
                    "date": "2024-10-18",
                    "departure": "San Francisco",
                    "destination": "Boston",
                    "departure_time": "10:45 PM",
                    "arrival_time": "01:15 AM",
                    "flight_duration": 1.0,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 46",
                    "total_passengers": 6,
                    " ": "16D",
                    " ": "REF-1045",
                    " ": "Credit Card",
                    " ": 20,
                    " ": "A6",
                    "terminal": "2",
                    "layover": "1 Stop",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                },
                {
                    "id": 47,
                    "flight": "Flight-146",
                    "airline": "SkyJet Airlines",
                    "date": "2024-11-19",
                    "departure": "Seattle",
                    "destination": "Houston",
                    "departure_time": "11:50 AM",
                    "arrival_time": "02:22 PM",
                    "flight_duration": 2.5,
                    "status": "Completed",
                    "amount_earn": 1300,
                    "passenger_name": "Passenger 47",
                    "total_passengers": 9,
                    " ": "17E",
                    " ": "REF-1046",
                    " ": "PayPal",
                    " ": 25,
                    " ": "B7",
                    "terminal": "3",
                    "layover": "3 stops",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "Silver Member"
                },
                {
                    "id": 48,
                    "flight": "Flight-147",
                    "airline": "AirLux",
                    "date": "2024-12-20",
                    "departure": "Denver",
                    "destination": "Los Angeles",
                    "departure_time": "12:55 PM",
                    "arrival_time": "03:29 AM",
                    "flight_duration": 4.0,
                    "status": "Cancled",
                    "amount_earn": 1600,
                    "passenger_name": "Passenger 48",
                    "total_passengers": 11,
                    " ": "18F",
                    " ": "REF-1047",
                    " ": "Bank Transfer",
                    " ": 30,
                    " ": "C8",
                    "terminal": "4",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Platinum Member"
                },
                {
                    "id": 49,
                    "flight": "Flight-148",
                    "airline": "Elite Airways",
                    "date": "2024-01-21",
                    "departure": "Boston",
                    "destination": "Miami",
                    "departure_time": "01:00 AM",
                    "arrival_time": "04:36 PM",
                    "flight_duration": 4.0,
                    "status": "Completed",
                    "amount_earn": 700,
                    "passenger_name": "Passenger 49",
                    "total_passengers": 6,
                    " ": "19A",
                    " ": "REF-1048",
                    " ": "Credit Card",
                    " ": 15,
                    " ": "D9",
                    "terminal": "1",
                    "layover": "1 Stop",
                    " ": "Refundable",
                    " ": "Completed",
                    " ": "3 stops"
                },
                {
                    "id": 50,
                    "flight": "Flight-149",
                    "airline": "PrivateFly",
                    "date": "2024-02-22",
                    "departure": "Houston",
                    "destination": "San Francisco",
                    "departure_time": "02:05 PM",
                    "arrival_time": "05:43 AM",
                    "flight_duration": 5.5,
                    "status": "Cancled",
                    "amount_earn": 1000,
                    "passenger_name": "Passenger 50",
                    "total_passengers": 9,
                    " ": "20B",
                    " ": "REF-1049",
                    " ": "PayPal",
                    " ": 20,
                    " ": "E10",
                    "terminal": "2",
                    "layover": "3 stops",
                    " ": "Non-refundable",
                    " ": "Pending",
                    " ": "Gold Member"
                }
            ]);
        }, 1000);
    });
};
