export const fetchConsumerHistory = async (email) => {
    console.log(`Fetching history for: ${email}`);

    return new Promise((resolve) => {
        setTimeout(() => {
            resolve([
                {
                    "id": 1,
                    "flight": "Flight-101",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-09",
                    "booking_start_date": "2025-02-23",
                    "departure": "Seattle",
                    "destination": "London",
                    "departure_time": "9:30 AM",
                    "boarding_time": "5:30 AM",
                    "gate_closing_time": "10:30 AM",
                    "arrival_time": "4:00 AM",
                    "flight_duration": "9h 30m",
                    "": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 783,
                    "": "USD",
                    "": "Passenger 1",
                    "": "First Class",
                    "": "9D",
                    "": "REF-1001",
                    "": "PayPal",
                    "Total_seats": 15,
                    "": "A2",
                    "terminal": "1",
                    "layover": "2 Stops",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "10:30 PM",
                    "Seats_booked": 12,
                    "": "Vegetarian",
                    "": "Extra Legroom",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1001.pdf"
                },
                {
                    "id": 2,
                    "flight": "Flight-102",
                    "airline": "BlueJet",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-09",
                    "booking_start_date": "2025-03-02",
                    "departure": "New York",
                    "destination": "Berlin",
                    "departure_time": "6:00 AM",
                    "boarding_time": "7:30 PM",
                    "gate_closing_time": "7:00 PM",
                    "arrival_time": "2:30 PM",
                    "flight_duration": "12h 30m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 135,
                    "": "USD",
                    "": "Passenger 2",
                    "": "First Class",
                    "": "9A",
                    "": "REF-1002",
                    "": "5",
                    "Total_seats": 20,
                    "": "B1",
                    "terminal": "5",
                    "layover": "Non-stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "9:30 AM",
                    "Seats_booked": "5",
                    "": "Vegetarian",
                    "": "Vegetarian Meal",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1002.pdf"
                },
                {
                    "id": 3,
                    "flight": "Flight-103",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-02-27",
                    "booking_start_date": "2025-02-12",
                    "departure": "New York",
                    "destination": "Berlin",
                    "departure_time": "4:30 AM",
                    "boarding_time": "3:30 PM",
                    "gate_closing_time": "10:00 PM",
                    "arrival_time": "1:30 PM",
                    "flight_duration": "8h 00m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 724,
                    "": "USD",
                    "": "Passenger 3",
                    "": "Economy",
                    "": "26B",
                    "": "REF-1003",
                    "": "5",
                    "Total_seats": 20,
                    "": "C3",
                    "terminal": "1",
                    "layover": "1 Stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "12:00 PM",
                    "Seats_booked": 2,
                    "": "Non-Vegetarian",
                    "": "Wheelchair Assistance",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1003.pdf"
                },
                {
                    "id": 4,
                    "flight": "Flight-104",
                    "airline": "JetX Airways",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-15",
                    "booking_start_date": "2025-03-08",
                    "departure": "Seattle",
                    "destination": "London",
                    "departure_time": "2:00 PM",
                    "boarding_time": "1:30 PM",
                    "gate_closing_time": "5:00 AM",
                    "arrival_time": "12:30 PM",
                    "flight_duration": "11h 00m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 4",
                    "": "Economy",
                    "": "5C",
                    "": "REF-1004",
                    "": "Bank Transfer",
                    "Total_seats": 20,
                    "": "B1",
                    "terminal": "1",
                    "layover": "Non-stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "3:00 PM",
                    "Seats_booked": 12,
                    "": "Non-Vegetarian",
                    "": "Wheelchair Assistance",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1004.pdf"
                },
                {
                    "id": 5,
                    "flight": "Flight-105",
                    "airline": "CloudNine",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-27",
                    "booking_start_date": "2025-03-19",
                    "departure": "Miami",
                    "destination": "Toronto",
                    "departure_time": "11:00 PM",
                    "boarding_time": "2:30 AM",
                    "gate_closing_time": "9:30 AM",
                    "arrival_time": "7:00 PM",
                    "flight_duration": "9h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 490,
                    "": "USD",
                    "": "Passenger 5",
                    "": "Economy",
                    "": "35B",
                    "": "REF-1005",
                    "": "Credit Card",
                    "Total_seats": 20,
                    "": "C5",
                    "terminal": "3",
                    "layover": "Non-stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "9:30 PM",
                    "Seats_booked": 2,
                    "": "5",
                    "": "Extra Legroom",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1005.pdf"
                },
                {
                    "id": 6,
                    "flight": "Flight-106",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-24",
                    "booking_start_date": "2025-03-10",
                    "departure": "Chicago",
                    "destination": "Toronto",
                    "departure_time": "1:30 AM",
                    "boarding_time": "7:00 PM",
                    "gate_closing_time": "6:00 PM",
                    "arrival_time": "7:30 PM",
                    "flight_duration": "9h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 6",
                    "": "Business",
                    "": "29B",
                    "": "REF-1006",
                    "": "Credit Card",
                    "Total_seats": 25,
                    "": "C7",
                    "terminal": 2,
                    "layover": "2 Stops",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "5:30 AM",
                    "Seats_booked": "10",
                    "": "Vegan",
                    "": "Extra Legroom",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1006.pdf"
                },
                {
                    "id": 7,
                    "flight": "Flight-107",
                    "airline": "JetX Airways",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-04-27",
                    "booking_start_date": "2025-04-17",
                    "departure": "New York",
                    "destination": "Tokyo",
                    "departure_time": "11:30 PM",
                    "boarding_time": "2:30 AM",
                    "gate_closing_time": "6:00 PM",
                    "arrival_time": "9:00 PM",
                    "flight_duration": "11h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 152,
                    "": "USD",
                    "": "Passenger 7",
                    "": "First Class",
                    "": "49C",
                    "": "REF-1007",
                    "": "Bank Transfer",
                    "Total_seats": 15,
                    "": "C2",
                    "terminal": "5",
                    "layover": "Non-stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "4:30 PM",
                    "Seats_booked": 12,
                    "": "Non-Vegetarian",
                    "": "Vegetarian Meal",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1007.pdf"
                },
                {
                    "id": 8,
                    "flight": "Flight-108",
                    "airline": "CloudNine",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-21",
                    "booking_start_date": "2025-03-07",
                    "departure": "Los Angeles",
                    "destination": "London",
                    "departure_time": "2:00 AM",
                    "boarding_time": "10:00 AM",
                    "gate_closing_time": "10:00 AM",
                    "arrival_time": "5:30 AM",
                    "flight_duration": "2h 30m",
                    "status": "Completed",
                    "missed_status": "Not Missed",
                    "amount_earn": 464,
                    "": "USD",
                    "": "Passenger 8",
                    "": "Business",
                    "": "37C",
                    "": "REF-1008",
                    "": "PayPal",
                    "Total_seats": 25,
                    "": "C3",
                    "terminal": 2,
                    "layover": "Non-stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "11:00 PM",
                    "Seats_booked": 2,
                    "": "Non-Vegetarian",
                    "": "5",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1008.pdf"
                },
                {
                    "id": 9,
                    "flight": "Flight-109",
                    "airline": "BlueJet",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-08",
                    "booking_start_date": "2025-03-03",
                    "departure": "New York",
                    "destination": "Paris",
                    "departure_time": "4:00 PM",
                    "boarding_time": "1:30 PM",
                    "gate_closing_time": "6:30 PM",
                    "arrival_time": "3:00 AM",
                    "flight_duration": "12h 00m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 9",
                    "": "Business",
                    "": "10A",
                    "": "REF-1009",
                    "": "PayPal",
                    "Total_seats": 15,
                    "": "A8",
                    "terminal": 2,
                    "layover": "2 Stops",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "7:00 PM",
                    "Seats_booked": "5",
                    "": "Vegetarian",
                    "": "Wheelchair Assistance",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1009.pdf"
                },
                {
                    "id": 10,
                    "flight": "Flight-110",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-02-28",
                    "booking_start_date": "2025-02-19",
                    "departure": "Miami",
                    "destination": "Paris",
                    "departure_time": "6:00 AM",
                    "boarding_time": "11:00 AM",
                    "gate_closing_time": "7:00 AM",
                    "arrival_time": "2:30 AM",
                    "flight_duration": "1h 00m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 271,
                    "": "USD",
                    "": "Passenger 10",
                    "": "Business",
                    "": "14A",
                    "": "REF-1010",
                    "": "Bank Transfer",
                    "Total_seats": 25,
                    "": "A5",
                    "terminal": "5",
                    "layover": "2 Stops",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "3:30 AM",
                    "Seats_booked": "10",
                    "": "Non-Vegetarian",
                    "": "Extra Legroom",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1010.pdf"
                },
                {
                    "id": 11,
                    "flight": "Flight-111",
                    "airline": "JetX Airways",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-04-22",
                    "booking_start_date": "2025-04-08",
                    "departure": "Dallas",
                    "destination": "Paris",
                    "departure_time": "9:00 AM",
                    "boarding_time": "2:00 PM",
                    "gate_closing_time": "7:00 PM",
                    "arrival_time": "11:30 PM",
                    "flight_duration": "6h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 329,
                    "": "USD",
                    "": "Passenger 11",
                    "": "Economy",
                    "": "46A",
                    "": "REF-1011",
                    "": "5",
                    "Total_seats": 25,
                    "": "C8",
                    "terminal": 2,
                    "layover": "Non-stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "12:30 PM",
                    "Seats_booked": "5",
                    "": "Vegan",
                    "": "Extra Legroom",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1011.pdf"
                },
                {
                    "id": 12,
                    "flight": "Flight-112",
                    "airline": "BlueJet",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-02-26",
                    "booking_start_date": "2025-02-06",
                    "departure": "Seattle",
                    "destination": "Berlin",
                    "departure_time": "10:30 PM",
                    "boarding_time": "2:30 AM",
                    "gate_closing_time": "5:00 AM",
                    "arrival_time": "9:30 AM",
                    "flight_duration": "5h 30m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 12",
                    "": "Economy",
                    "": "27A",
                    "": "REF-1012",
                    "": "Credit Card",
                    "Total_seats": 25,
                    "": "C8",
                    "terminal": "1",
                    "layover": "2 Stops",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "12:00 PM",
                    "Seats_booked": "10",
                    "": "Non-Vegetarian",
                    "": "5",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1012.pdf"
                },
                {
                    "id": 13,
                    "flight": "Flight-113",
                    "airline": "CloudNine",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-25",
                    "booking_start_date": "2025-03-07",
                    "departure": "Los Angeles",
                    "destination": "Dubai",
                    "departure_time": "2:30 AM",
                    "boarding_time": "8:30 PM",
                    "gate_closing_time": "1:30 AM",
                    "arrival_time": "5:30 AM",
                    "flight_duration": "9h 00m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 784,
                    "": "USD",
                    "": "Passenger 13",
                    "": "Economy",
                    "": "12C",
                    "": "REF-1013",
                    "": "Credit Card",
                    "Total_seats": 15,
                    "": "B10",
                    "terminal": "3",
                    "layover": "Non-stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "9:30 AM",
                    "Seats_booked": 12,
                    "": "5",
                    "": "Extra Legroom",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1013.pdf"
                },
                {
                    "id": 14,
                    "flight": "Flight-114",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-04-09",
                    "booking_start_date": "2025-03-30",
                    "departure": "Dallas",
                    "destination": "Berlin",
                    "departure_time": "2:30 PM",
                    "boarding_time": "9:30 PM",
                    "gate_closing_time": "5:00 PM",
                    "arrival_time": "1:30 PM",
                    "flight_duration": "8h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 14",
                    "": "Business",
                    "": "44C",
                    "": "REF-1014",
                    "": "Credit Card",
                    "Total_seats": 15,
                    "": "B5",
                    "terminal": 2,
                    "layover": "1 Stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "1:00 AM",
                    "Seats_booked": "10",
                    "": "Vegetarian",
                    "": "Extra Legroom",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1014.pdf"
                },
                {
                    "id": 15,
                    "flight": "Flight-115",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-04-15",
                    "booking_start_date": "2025-04-06",
                    "departure": "Chicago",
                    "destination": "London",
                    "departure_time": "8:30 PM",
                    "boarding_time": "12:30 AM",
                    "gate_closing_time": "1:00 PM",
                    "arrival_time": "4:00 PM",
                    "flight_duration": "3h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 15",
                    "": "Business",
                    "": "33C",
                    "": "REF-1015",
                    "": "PayPal",
                    "Total_seats": 20,
                    "": "A6",
                    "terminal": 2,
                    "layover": "Non-stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "11:00 PM",
                    "Seats_booked": "5",
                    "": "Vegan",
                    "": "5",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1015.pdf"
                },
                {
                    "id": 16,
                    "flight": "Flight-116",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-04-12",
                    "booking_start_date": "2025-04-03",
                    "departure": "New York",
                    "destination": "Tokyo",
                    "departure_time": "10:30 AM",
                    "boarding_time": "4:00 PM",
                    "gate_closing_time": "7:00 PM",
                    "arrival_time": "3:30 AM",
                    "flight_duration": "10h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 886,
                    "": "USD",
                    "": "Passenger 16",
                    "": "First Class",
                    "": "45C",
                    "": "REF-1016",
                    "": "5",
                    "Total_seats": 20,
                    "": "B8",
                    "terminal": "5",
                    "layover": "2 Stops",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "11:30 PM",
                    "Seats_booked": "5",
                    "": "Vegan",
                    "": "Extra Legroom",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1016.pdf"
                },
                {
                    "id": 17,
                    "flight": "Flight-117",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-26",
                    "booking_start_date": "2025-03-21",
                    "departure": "Miami",
                    "destination": "Toronto",
                    "departure_time": "10:30 PM",
                    "boarding_time": "2:30 PM",
                    "gate_closing_time": "11:00 PM",
                    "arrival_time": "3:30 AM",
                    "flight_duration": "4h 30m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 886,
                    "": "USD",
                    "": "Passenger 17",
                    "": "Business",
                    "": "9C",
                    "": "REF-1017",
                    "": "5",
                    "Total_seats": 15,
                    "": "C1",
                    "terminal": "4",
                    "layover": "Non-stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "9:30 PM",
                    "Seats_booked": 2,
                    "": "Vegetarian",
                    "": "Vegetarian Meal",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1017.pdf"
                },
                {
                    "id": 18,
                    "flight": "Flight-118",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-18",
                    "booking_start_date": "2025-03-02",
                    "departure": "New York",
                    "destination": "Berlin",
                    "departure_time": "10:30 PM",
                    "boarding_time": "4:00 AM",
                    "gate_closing_time": "11:00 PM",
                    "arrival_time": "11:30 AM",
                    "flight_duration": "11h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 18",
                    "": "Business",
                    "": "19B",
                    "": "REF-1018",
                    "": "PayPal",
                    "Total_seats": 15,
                    "": "A4",
                    "terminal": 2,
                    "layover": "1 Stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "9:00 PM",
                    "Seats_booked": "10",
                    "": "Vegan",
                    "": "Vegetarian Meal",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1018.pdf"
                },
                {
                    "id": 19,
                    "flight": "Flight-119",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-04-17",
                    "booking_start_date": "2025-04-03",
                    "departure": "Dallas",
                    "destination": "Toronto",
                    "departure_time": "11:00 AM",
                    "boarding_time": "2:00 PM",
                    "gate_closing_time": "8:00 PM",
                    "arrival_time": "12:00 AM",
                    "flight_duration": "3h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 713,
                    "": "USD",
                    "": "Passenger 19",
                    "": "Business",
                    "": "36B",
                    "": "REF-1019",
                    "": "Bank Transfer",
                    "Total_seats": 25,
                    "": "B3",
                    "terminal": 2,
                    "layover": "2 Stops",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "3:30 AM",
                    "Seats_booked": 2,
                    "": "Non-Vegetarian",
                    "": "5",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1019.pdf"
                },
                {
                    "id": 20,
                    "flight": "Flight-120",
                    "airline": "CloudNine",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-27",
                    "booking_start_date": "2025-03-15",
                    "departure": "Dallas",
                    "destination": "Dubai",
                    "departure_time": "12:00 AM",
                    "boarding_time": "4:30 AM",
                    "gate_closing_time": "11:00 PM",
                    "arrival_time": "5:00 PM",
                    "flight_duration": "4h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 20",
                    "": "Business",
                    "": "18D",
                    "": "REF-1020",
                    "": "5",
                    "Total_seats": 20,
                    "": "C6",
                    "terminal": "5",
                    "layover": "1 Stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "7:00 PM",
                    "Seats_booked": 12,
                    "": "5",
                    "": "5",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1020.pdf"
                },
                {
                    "id": 21,
                    "flight": "Flight-121",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-19",
                    "booking_start_date": "2025-02-27",
                    "departure": "Los Angeles",
                    "destination": "Dubai",
                    "departure_time": "12:30 PM",
                    "boarding_time": "1:30 AM",
                    "gate_closing_time": "11:30 AM",
                    "arrival_time": "3:30 AM",
                    "flight_duration": "8h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 21",
                    "": "Economy",
                    "": "10C",
                    "": "REF-1021",
                    "": "PayPal",
                    "Total_seats": 15,
                    "": "A7",
                    "terminal": "3",
                    "layover": "Non-stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "4:00 PM",
                    "Seats_booked": "5",
                    "": "5",
                    "": "Wheelchair Assistance",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1021.pdf"
                },
                {
                    "id": 22,
                    "flight": "Flight-122",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-04-05",
                    "booking_start_date": "2025-03-18",
                    "departure": "Los Angeles",
                    "destination": "Dubai",
                    "departure_time": "9:00 PM",
                    "boarding_time": "6:30 AM",
                    "gate_closing_time": "8:00 AM",
                    "arrival_time": "8:00 AM",
                    "flight_duration": "4h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 22",
                    "": "First Class",
                    "": "1A",
                    "": "REF-1022",
                    "": "Credit Card",
                    "Total_seats": 20,
                    "": "C6",
                    "terminal": 2,
                    "layover": "2 Stops",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "10:00 PM",
                    "Seats_booked": 2,
                    "": "Non-Vegetarian",
                    "": "Wheelchair Assistance",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1022.pdf"
                },
                {
                    "id": 23,
                    "flight": "Flight-123",
                    "airline": "BlueJet",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-31",
                    "booking_start_date": "2025-03-15",
                    "departure": "Miami",
                    "destination": "Paris",
                    "departure_time": "7:30 AM",
                    "boarding_time": "11:00 AM",
                    "gate_closing_time": "12:00 PM",
                    "arrival_time": "3:00 PM",
                    "flight_duration": "4h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 23",
                    "": "Economy",
                    "": "20C",
                    "": "REF-1023",
                    "": "Bank Transfer",
                    "Total_seats": 25,
                    "": "B2",
                    "terminal": 2,
                    "layover": "Non-stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "3:00 AM",
                    "Seats_booked": 12,
                    "": "Vegan",
                    "": "Extra Legroom",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1023.pdf"
                },
                {
                    "id": 24,
                    "flight": "Flight-124",
                    "airline": "BlueJet",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-14",
                    "booking_start_date": "2025-02-26",
                    "departure": "Los Angeles",
                    "destination": "Berlin",
                    "departure_time": "2:00 PM",
                    "boarding_time": "9:30 AM",
                    "gate_closing_time": "4:00 PM",
                    "arrival_time": "2:30 PM",
                    "flight_duration": "9h 30m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 24",
                    "": "First Class",
                    "": "24D",
                    "": "REF-1024",
                    "": "Credit Card",
                    "Total_seats": 25,
                    "": "B5",
                    "terminal": "1",
                    "layover": "Non-stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "6:00 AM",
                    "Seats_booked": "10",
                    "": "Vegan",
                    "": "Extra Legroom",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1024.pdf"
                },
                {
                    "id": 25,
                    "flight": "Flight-125",
                    "airline": "CloudNine",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-04-19",
                    "booking_start_date": "2025-03-30",
                    "departure": "Chicago",
                    "destination": "Toronto",
                    "departure_time": "1:30 AM",
                    "boarding_time": "11:30 PM",
                    "gate_closing_time": "4:00 AM",
                    "arrival_time": "6:00 AM",
                    "flight_duration": "7h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 900,
                    "": "USD",
                    "": "Passenger 25",
                    "": "Economy",
                    "": "36D",
                    "": "REF-1025",
                    "": "PayPal",
                    "Total_seats": 15,
                    "": "C6",
                    "terminal": "1",
                    "layover": "2 Stops",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "1:30 AM",
                    "Seats_booked": 12,
                    "": "5",
                    "": "5",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1025.pdf"
                },
                {
                    "id": 26,
                    "flight": "Flight-126",
                    "airline": "CloudNine",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-17",
                    "booking_start_date": "2025-03-04",
                    "departure": "New York",
                    "destination": "Berlin",
                    "departure_time": "12:30 AM",
                    "boarding_time": "7:00 PM",
                    "gate_closing_time": "1:00 PM",
                    "arrival_time": "8:30 AM",
                    "flight_duration": "12h 30m",
                    "status": "Completed",
                    "missed_status": "Not Missed",
                    "amount_earn": 534,
                    "": "USD",
                    "": "Passenger 26",
                    "": "First Class",
                    "": "22D",
                    "": "REF-1026",
                    "": "Credit Card",
                    "Total_seats": 15,
                    "": "A8",
                    "terminal": 2,
                    "layover": "2 Stops",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "12:30 AM",
                    "Seats_booked": 2,
                    "": "Non-Vegetarian",
                    "": "Wheelchair Assistance",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1026.pdf"
                },
                {
                    "id": 27,
                    "flight": "Flight-127",
                    "airline": "CloudNine",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-16",
                    "booking_start_date": "2025-02-28",
                    "departure": "Los Angeles",
                    "destination": "Tokyo",
                    "departure_time": "5:00 AM",
                    "boarding_time": "9:30 PM",
                    "gate_closing_time": "8:30 PM",
                    "arrival_time": "2:30 AM",
                    "flight_duration": "9h 30m",
                    "status": "Completed",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 27",
                    "": "Economy",
                    "": "16C",
                    "": "REF-1027",
                    "": "5",
                    "Total_seats": 15,
                    "": "A10",
                    "terminal": "5",
                    "layover": "2 Stops",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "2:00 PM",
                    "Seats_booked": "10",
                    "": "Non-Vegetarian",
                    "": "Wheelchair Assistance",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1027.pdf"
                },
                {
                    "id": 28,
                    "flight": "Flight-128",
                    "airline": "BlueJet",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-04-02",
                    "booking_start_date": "2025-03-13",
                    "departure": "Los Angeles",
                    "destination": "Paris",
                    "departure_time": "7:00 PM",
                    "boarding_time": "1:00 AM",
                    "gate_closing_time": "11:30 AM",
                    "arrival_time": "1:30 PM",
                    "flight_duration": "6h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 344,
                    "": "USD",
                    "": "Passenger 28",
                    "": "First Class",
                    "": "28B",
                    "": "REF-1028",
                    "": "Bank Transfer",
                    "Total_seats": 25,
                    "": "B6",
                    "terminal": "5",
                    "layover": "1 Stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "11:00 PM",
                    "Seats_booked": "10",
                    "": "Vegetarian",
                    "": "Vegetarian Meal",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1028.pdf"
                },
                {
                    "id": 29,
                    "flight": "Flight-129",
                    "airline": "JetX Airways",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-23",
                    "booking_start_date": "2025-03-15",
                    "departure": "Los Angeles",
                    "destination": "London",
                    "departure_time": "9:30 PM",
                    "boarding_time": "8:30 PM",
                    "gate_closing_time": "4:00 PM",
                    "arrival_time": "12:30 PM",
                    "flight_duration": "11h 00m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 354,
                    "": "USD",
                    "": "Passenger 29",
                    "": "Business",
                    "": "50C",
                    "": "REF-1029",
                    "": "Credit Card",
                    "Total_seats": 25,
                    "": "A4",
                    "terminal": 2,
                    "layover": "1 Stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "7:00 PM",
                    "Seats_booked": 12,
                    "": "Vegan",
                    "": "Extra Legroom",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1029.pdf"
                },
                {
                    "id": 30,
                    "flight": "Flight-130",
                    "airline": "CloudNine",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-04-06",
                    "booking_start_date": "2025-03-31",
                    "departure": "Miami",
                    "destination": "Paris",
                    "departure_time": "5:00 PM",
                    "boarding_time": "10:00 PM",
                    "gate_closing_time": "3:00 PM",
                    "arrival_time": "7:30 AM",
                    "flight_duration": "12h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 30",
                    "": "Business",
                    "": "11C",
                    "": "REF-1030",
                    "": "Bank Transfer",
                    "Total_seats": 15,
                    "": "A1",
                    "terminal": "5",
                    "layover": "2 Stops",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "11:30 PM",
                    "Seats_booked": 2,
                    "": "Non-Vegetarian",
                    "": "5",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1030.pdf"
                },
                {
                    "id": 31,
                    "flight": "Flight-131",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-04-02",
                    "booking_start_date": "2025-03-18",
                    "departure": "Los Angeles",
                    "destination": "Paris",
                    "departure_time": "8:00 AM",
                    "boarding_time": "4:30 AM",
                    "gate_closing_time": "1:30 PM",
                    "arrival_time": "10:00 AM",
                    "flight_duration": "4h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 308,
                    "": "USD",
                    "": "Passenger 31",
                    "": "First Class",
                    "": "17D",
                    "": "REF-1031",
                    "": "Credit Card",
                    "Total_seats": 15,
                    "": "B9",
                    "terminal": 2,
                    "layover": "1 Stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "9:30 PM",
                    "Seats_booked": 2,
                    "": "Non-Vegetarian",
                    "": "Vegetarian Meal",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1031.pdf"
                },
                {
                    "id": 32,
                    "flight": "Flight-132",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-04",
                    "booking_start_date": "2025-02-21",
                    "departure": "Los Angeles",
                    "destination": "London",
                    "departure_time": "8:30 PM",
                    "boarding_time": "2:30 PM",
                    "gate_closing_time": "11:30 PM",
                    "arrival_time": "4:30 AM",
                    "flight_duration": "1h 00m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 32",
                    "": "Economy",
                    "": "19C",
                    "": "REF-1032",
                    "": "5",
                    "Total_seats": 15,
                    "": "B7",
                    "terminal": "5",
                    "layover": "Non-stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "9:00 AM",
                    "Seats_booked": 2,
                    "": "Non-Vegetarian",
                    "": "Wheelchair Assistance",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1032.pdf"
                },
                {
                    "id": 33,
                    "flight": "Flight-133",
                    "airline": "CloudNine",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-04-04",
                    "booking_start_date": "2025-03-25",
                    "departure": "Seattle",
                    "destination": "Paris",
                    "departure_time": "3:30 AM",
                    "boarding_time": "10:00 AM",
                    "gate_closing_time": "8:30 PM",
                    "arrival_time": "4:30 AM",
                    "flight_duration": "4h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 33",
                    "": "Economy",
                    "": "3A",
                    "": "REF-1033",
                    "": "Bank Transfer",
                    "Total_seats": 20,
                    "": "C6",
                    "terminal": "4",
                    "layover": "2 Stops",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "10:30 PM",
                    "Seats_booked": 12,
                    "": "Vegetarian",
                    "": "Extra Legroom",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1033.pdf"
                },
                {
                    "id": 34,
                    "flight": "Flight-134",
                    "airline": "BlueJet",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-04-17",
                    "booking_start_date": "2025-04-01",
                    "departure": "Seattle",
                    "destination": "London",
                    "departure_time": "4:00 AM",
                    "boarding_time": "12:30 AM",
                    "gate_closing_time": "5:30 PM",
                    "arrival_time": "7:30 AM",
                    "flight_duration": "1h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 142,
                    "": "USD",
                    "": "Passenger 34",
                    "": "First Class",
                    "": "33B",
                    "": "REF-1034",
                    "": "5",
                    "Total_seats": 25,
                    "": "A6",
                    "terminal": "4",
                    "layover": "1 Stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "5:30 AM",
                    "Seats_booked": 12,
                    "": "Non-Vegetarian",
                    "": "5",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1034.pdf"
                },
                {
                    "id": 35,
                    "flight": "Flight-135",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-09",
                    "booking_start_date": "2025-03-01",
                    "departure": "Dallas",
                    "destination": "London",
                    "departure_time": "10:30 AM",
                    "boarding_time": "7:30 AM",
                    "gate_closing_time": "9:00 AM",
                    "arrival_time": "5:00 PM",
                    "flight_duration": "12h 30m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 35",
                    "": "Economy",
                    "": "46C",
                    "": "REF-1035",
                    "": "Credit Card",
                    "Total_seats": 25,
                    "": "B8",
                    "terminal": "1",
                    "layover": "Non-stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "8:00 PM",
                    "Seats_booked": "5",
                    "": "5",
                    "": "Vegetarian Meal",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1035.pdf"
                },
                {
                    "id": 36,
                    "flight": "Flight-136",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-04-25",
                    "booking_start_date": "2025-04-05",
                    "departure": "Miami",
                    "destination": "Toronto",
                    "departure_time": "2:00 PM",
                    "boarding_time": "5:00 PM",
                    "gate_closing_time": "1:30 PM",
                    "arrival_time": "8:00 PM",
                    "flight_duration": "1h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 293,
                    "": "USD",
                    "": "Passenger 36",
                    "": "Business",
                    "": "5B",
                    "": "REF-1036",
                    "": "5",
                    "Total_seats": 25,
                    "": "B10",
                    "terminal": "3",
                    "layover": "1 Stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "6:00 AM",
                    "Seats_booked": "5",
                    "": "5",
                    "": "Extra Legroom",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1036.pdf"
                },
                {
                    "id": 37,
                    "flight": "Flight-137",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-06",
                    "booking_start_date": "2025-03-01",
                    "departure": "Seattle",
                    "destination": "Dubai",
                    "departure_time": "12:00 AM",
                    "boarding_time": "6:00 AM",
                    "gate_closing_time": "9:00 PM",
                    "arrival_time": "6:00 PM",
                    "flight_duration": "3h 30m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 693,
                    "": "USD",
                    "": "Passenger 37",
                    "": "Economy",
                    "": "50A",
                    "": "REF-1037",
                    "": "5",
                    "Total_seats": 25,
                    "": "B8",
                    "terminal": "5",
                    "layover": "2 Stops",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "5:00 AM",
                    "Seats_booked": "5",
                    "": "Vegan",
                    "": "Vegetarian Meal",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1037.pdf"
                },
                {
                    "id": 38,
                    "flight": "Flight-138",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-04-11",
                    "booking_start_date": "2025-03-27",
                    "departure": "Miami",
                    "destination": "Paris",
                    "departure_time": "12:00 AM",
                    "boarding_time": "4:30 AM",
                    "gate_closing_time": "1:00 AM",
                    "arrival_time": "3:30 PM",
                    "flight_duration": "10h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 905,
                    "": "USD",
                    "": "Passenger 38",
                    "": "First Class",
                    "": "14B",
                    "": "REF-1038",
                    "": "Credit Card",
                    "Total_seats": 25,
                    "": "C7",
                    "terminal": "1",
                    "layover": "2 Stops",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "9:00 PM",
                    "Seats_booked": 12,
                    "": "Non-Vegetarian",
                    "": "Extra Legroom",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1038.pdf"
                },
                {
                    "id": 39,
                    "flight": "Flight-139",
                    "airline": "BlueJet",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-04-17",
                    "booking_start_date": "2025-04-01",
                    "departure": "New York",
                    "destination": "Paris",
                    "departure_time": "7:30 PM",
                    "boarding_time": "12:30 AM",
                    "gate_closing_time": "5:30 PM",
                    "arrival_time": "12:00 PM",
                    "flight_duration": "12h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 39",
                    "": "First Class",
                    "": "5C",
                    "": "REF-1039",
                    "": "5",
                    "Total_seats": 20,
                    "": "C5",
                    "terminal": 2,
                    "layover": "2 Stops",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "10:00 AM",
                    "Seats_booked": "10",
                    "": "Vegan",
                    "": "Extra Legroom",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1039.pdf"
                },
                {
                    "id": 40,
                    "flight": "Flight-140",
                    "airline": "BlueJet",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-11",
                    "booking_start_date": "2025-03-02",
                    "departure": "Chicago",
                    "destination": "Tokyo",
                    "departure_time": "6:00 AM",
                    "boarding_time": "12:30 AM",
                    "gate_closing_time": "12:00 AM",
                    "arrival_time": "11:00 PM",
                    "flight_duration": "12h 30m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 637,
                    "": "USD",
                    "": "Passenger 40",
                    "": "First Class",
                    "": "15A",
                    "": "REF-1040",
                    "": "Bank Transfer",
                    "Total_seats": 20,
                    "": "A10",
                    "terminal": "3",
                    "layover": "1 Stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "4:30 AM",
                    "Seats_booked": "10",
                    "": "5",
                    "": "Wheelchair Assistance",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1040.pdf"
                },
                {
                    "id": 41,
                    "flight": "Flight-141",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-25",
                    "booking_start_date": "2025-03-09",
                    "departure": "Dallas",
                    "destination": "Toronto",
                    "departure_time": "5:00 PM",
                    "boarding_time": "6:00 PM",
                    "gate_closing_time": "10:00 AM",
                    "arrival_time": "1:00 AM",
                    "flight_duration": "7h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 41",
                    "": "First Class",
                    "": "16D",
                    "": "REF-1041",
                    "": "Bank Transfer",
                    "Total_seats": 25,
                    "": "C6",
                    "terminal": "4",
                    "layover": "Non-stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "5:30 AM",
                    "Seats_booked": "5",
                    "": "Non-Vegetarian",
                    "": "Wheelchair Assistance",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1041.pdf"
                },
                {
                    "id": 42,
                    "flight": "Flight-142",
                    "airline": "CloudNine",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-11",
                    "booking_start_date": "2025-02-22",
                    "departure": "Seattle",
                    "destination": "Dubai",
                    "departure_time": "10:00 AM",
                    "boarding_time": "6:00 AM",
                    "gate_closing_time": "12:00 AM",
                    "arrival_time": "11:30 AM",
                    "flight_duration": "2h 30m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 341,
                    "": "USD",
                    "": "Passenger 42",
                    "": "First Class",
                    "": "30C",
                    "": "REF-1042",
                    "": "Bank Transfer",
                    "Total_seats": 15,
                    "": "A3",
                    "terminal": "3",
                    "layover": "2 Stops",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "12:00 PM",
                    "Seats_booked": 12,
                    "": "Vegetarian",
                    "": "Vegetarian Meal",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1042.pdf"
                },
                {
                    "id": 43,
                    "flight": "Flight-143",
                    "airline": "JetX Airways",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-31",
                    "booking_start_date": "2025-03-12",
                    "departure": "Miami",
                    "destination": "London",
                    "departure_time": "10:30 PM",
                    "boarding_time": "5:00 PM",
                    "gate_closing_time": "10:30 PM",
                    "arrival_time": "9:30 PM",
                    "flight_duration": "11h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 43",
                    "": "Economy",
                    "": "24B",
                    "": "REF-1043",
                    "": "PayPal",
                    "Total_seats": 25,
                    "": "C2",
                    "terminal": "1",
                    "layover": "1 Stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "2:30 AM",
                    "Seats_booked": 12,
                    "": "Vegan",
                    "": "Vegetarian Meal",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1043.pdf"
                },
                {
                    "id": 44,
                    "flight": "Flight-144",
                    "airline": "JetX Airways",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-16",
                    "booking_start_date": "2025-02-25",
                    "departure": "New York",
                    "destination": "Dubai",
                    "departure_time": "7:30 PM",
                    "boarding_time": "11:00 AM",
                    "gate_closing_time": "11:30 PM",
                    "arrival_time": "4:30 PM",
                    "flight_duration": "8h 00m",
                    "status": "Completed",
                    "missed_status": "Missed",
                    "amount_earn": 195,
                    "": "USD",
                    "": "Passenger 44",
                    "": "First Class",
                    "": "3D",
                    "": "REF-1044",
                    "": "Credit Card",
                    "Total_seats": 20,
                    "": "C2",
                    "terminal": "5",
                    "layover": "2 Stops",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "11:00 PM",
                    "Seats_booked": 12,
                    "": "Vegetarian",
                    "": "5",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1044.pdf"
                },
                {
                    "id": 45,
                    "flight": "Flight-145",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-22",
                    "booking_start_date": "2025-03-10",
                    "departure": "Seattle",
                    "destination": "Berlin",
                    "departure_time": "3:30 AM",
                    "boarding_time": "11:00 PM",
                    "gate_closing_time": "11:00 AM",
                    "arrival_time": "1:00 AM",
                    "flight_duration": "9h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 737,
                    "": "USD",
                    "": "Passenger 45",
                    "": "Business",
                    "": "49B",
                    "": "REF-1045",
                    "": "PayPal",
                    "Total_seats": 25,
                    "": "B1",
                    "terminal": "3",
                    "layover": "1 Stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "2:00 AM",
                    "Seats_booked": 12,
                    "": "Vegetarian",
                    "": "Vegetarian Meal",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1045.pdf"
                },
                {
                    "id": 46,
                    "flight": "Flight-146",
                    "airline": "JetX Airways",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-04-01",
                    "booking_start_date": "2025-03-22",
                    "departure": "Seattle",
                    "destination": "Dubai",
                    "departure_time": "3:00 PM",
                    "boarding_time": "6:00 PM",
                    "gate_closing_time": "2:30 PM",
                    "arrival_time": "4:00 AM",
                    "flight_duration": "11h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 165,
                    "": "USD",
                    "": "Passenger 46",
                    "": "Economy",
                    "": "34A",
                    "": "REF-1046",
                    "": "5",
                    "Total_seats": 15,
                    "": "A3",
                    "terminal": "3",
                    "layover": "1 Stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "6:30 PM",
                    "Seats_booked": 12,
                    "": "Non-Vegetarian",
                    "": "Wheelchair Assistance",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1046.pdf"
                },
                {
                    "id": 47,
                    "flight": "Flight-147",
                    "airline": "JetX Airways",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-03-23",
                    "booking_start_date": "2025-03-06",
                    "departure": "New York",
                    "destination": "Paris",
                    "departure_time": "1:00 PM",
                    "boarding_time": "11:00 AM",
                    "gate_closing_time": "10:30 AM",
                    "arrival_time": "9:30 PM",
                    "flight_duration": "5h 00m",
                    "status": "Completed",
                    "missed_status": "Not Missed",
                    "amount_earn": 458,
                    "": "USD",
                    "": "Passenger 47",
                    "": "Business",
                    "": "16D",
                    "": "REF-1047",
                    "": "Credit Card",
                    "Total_seats": 20,
                    "": "B7",
                    "terminal": "1",
                    "layover": "Non-stop",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "1:30 AM",
                    "Seats_booked": "10",
                    "": "5",
                    "": "5",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1047.pdf"
                },
                {
                    "id": 48,
                    "flight": "Flight-148",
                    "airline": "AeroFly",
                    "airplane_model": "Boeing 737",
                    "flight_type": "Domestic",
                    "date": "2025-03-25",
                    "booking_start_date": "2025-03-19",
                    "departure": "Miami",
                    "destination": "Tokyo",
                    "departure_time": "3:30 PM",
                    "boarding_time": "2:00 PM",
                    "gate_closing_time": "3:30 AM",
                    "arrival_time": "8:00 AM",
                    "flight_duration": "10h 30m",
                    "status": "Completed",
                    "missed_status": "Not Missed",
                    "amount_earn": 882,
                    "": "USD",
                    "": "Passenger 48",
                    "": "Economy",
                    "": "17B",
                    "": "REF-1048",
                    "": "PayPal",
                    "Total_seats": 15,
                    "": "C2",
                    "terminal": 2,
                    "layover": "1 Stop",
                    "cancellation_policy": "Non-refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "11:30 AM",
                    "Seats_booked": "5",
                    "": "Vegan",
                    "": "Vegetarian Meal",
                    "": "Yes",
                    "": "https://yourwebsite.com/tickets/REF-1048.pdf"
                },
                {
                    "id": 49,
                    "flight": "Flight-149",
                    "airline": "BlueJet",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-04-04",
                    "booking_start_date": "2025-03-19",
                    "departure": "Los Angeles",
                    "destination": "Berlin",
                    "departure_time": "1:00 AM",
                    "boarding_time": "10:00 PM",
                    "gate_closing_time": "4:30 PM",
                    "arrival_time": "11:30 AM",
                    "flight_duration": "9h 00m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 0,
                    "": "USD",
                    "": "Passenger 49",
                    "": "Business",
                    "": "46B",
                    "": "REF-1049",
                    "": "PayPal",
                    "Total_seats": 25,
                    "": "A1",
                    "terminal": "1",
                    "layover": "2 Stops",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Pending",
                    "check_in_deadline": "9:00 AM",
                    "Seats_booked": "10",
                    "": "5",
                    "": "Extra Legroom",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1049.pdf"
                },
                {
                    "id": 50,
                    "flight": "Flight-150",
                    "airline": "SkyHigh",
                    "airplane_model": "Boeing 737",
                    "flight_type": "International",
                    "date": "2025-04-14",
                    "booking_start_date": "2025-04-03",
                    "departure": "Seattle",
                    "destination": "Dubai",
                    "departure_time": "5:30 AM",
                    "boarding_time": "10:30 PM",
                    "gate_closing_time": "2:00 AM",
                    "arrival_time": "1:30 PM",
                    "flight_duration": "3h 30m",
                    "status": "Upcoming",
                    "missed_status": "Not Missed",
                    "amount_earn": 618,
                    "": "USD",
                    "": "Passenger 50",
                    "": "Business",
                    "": "41A",
                    "": "REF-1050",
                    "": "5",
                    "Total_seats": 25,
                    "": "C4",
                    "terminal": "1",
                    "layover": "2 Stops",
                    "cancellation_policy": "Refundable",
                    "check_in_status": "Checked-in",
                    "check_in_deadline": "6:30 PM",
                    "Seats_booked": 12,
                    "": "Vegan",
                    "": "Vegetarian Meal",
                    "": "No",
                    "": "https://yourwebsite.com/tickets/REF-1050.pdf"
                }
            ]);
        }, 1000);
    });
};
